import React, { memo, useMemo } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import dynamic from "next/dynamic";

import Header from "../header/Header";
import Footer from "../../common/Footer";

const AdminLayout = dynamic(() => import("../admin/AdminLayout"), {
  ssr: false,
  loading: () => <div className="text-center p-5">Loading Layout...</div>,
});

const MemoizedHeader = memo(Header);
const MemoizedFooter = memo(Footer);

function Layout({ children }) {
  const router = useRouter();

  const { isPanelPage, isAdminPanel } = useMemo(() => {
    const path = router.pathname;
    return {
      isPanelPage:
        path.startsWith("/admin-panel") ||
        path.startsWith("/attorney-panel") ||
        path.startsWith("/client-panel"),
      isAdminPanel: path.startsWith("/admin-panel"),
    };
  }, [router.pathname]);

  return (
    <>
      <Head>
        <title>Corelaw - Law firm</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {!isPanelPage && <MemoizedHeader />}

      <main>
        {isAdminPanel ? (
          <AdminLayout>{children}</AdminLayout>
        ) : (
          <div className="fade-in">{children}</div>
        )}
      </main>

      {!isPanelPage && <MemoizedFooter />}

      <style jsx>{`
        .fade-in {
          animation: fadeIn 0.3s ease-in-out;
        }
        @keyframes fadeIn {
          from {
            opacity: 0;
          }
          to {
            opacity: 1;
          }
        }
      `}</style>
    </>
  );
}

export default Layout;
