

import { useEffect, useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic"; // Import dynamic
import Banner1 from "../components/banner/Banner1";

// Import the popup only for this page
const DisclaimerPopup = dynamic(() => import("../components/DisclaimerPopup"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Lawfirm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/images/icons/logo-icon.svg" />
      </Head>

      {/* 1. Add the popup here */}
      <DisclaimerPopup />

      {/* 2. Your Page Content */}
      <Banner1 />

      {/* <Footer /> */}
    </>
  );
}
  